// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_eu7Or-_EBeuATSCX6wFUpX3UtGQRUCE',
    appId: '1:79236200072:web:5dd3d79dbb18ce9e2a913d',
    messagingSenderId: '79236200072',
    projectId: 'ick-2b00d',
    authDomain: 'ick-2b00d.firebaseapp.com',
    storageBucket: 'ick-2b00d.firebasestorage.app',
    measurementId: 'G-46VZ9TMHNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Q5UJ34hjW9Da7o_orctfNnl3b1ZSPIg',
    appId: '1:79236200072:android:58b12c05038e5a7a2a913d',
    messagingSenderId: '79236200072',
    projectId: 'ick-2b00d',
    storageBucket: 'ick-2b00d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYh_9ylciOONk2diCwvdZ0HLllTPmMNX0',
    appId: '1:79236200072:ios:e9ab440982c8b4d02a913d',
    messagingSenderId: '79236200072',
    projectId: 'ick-2b00d',
    storageBucket: 'ick-2b00d.firebasestorage.app',
    iosBundleId: 'com.shu.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYh_9ylciOONk2diCwvdZ0HLllTPmMNX0',
    appId: '1:79236200072:ios:e9ab440982c8b4d02a913d',
    messagingSenderId: '79236200072',
    projectId: 'ick-2b00d',
    storageBucket: 'ick-2b00d.firebasestorage.app',
    iosBundleId: 'com.shu.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_eu7Or-_EBeuATSCX6wFUpX3UtGQRUCE',
    appId: '1:79236200072:web:539177a9e06542ee2a913d',
    messagingSenderId: '79236200072',
    projectId: 'ick-2b00d',
    authDomain: 'ick-2b00d.firebaseapp.com',
    storageBucket: 'ick-2b00d.firebasestorage.app',
    measurementId: 'G-Z7K12N1ZZ9',
  );
}
